### PR TITLE
Moved entire project into gradle module.

### PR DESCRIPTION
**Pull request by TheColourRed**
Added necessary dependencies and removed library jars
Added gitignore for intellij and gradle files
added test class PacketDataSupportTest.java with empty test cases for now

### CODE REVIEW

**Comment by TheColourRed** [comment]
This changes the entire cnc-computer section into a gradle project. Tests can now be ran with the command "gradle test"

**Comment by ryanfrohar** [comment]
run tests

**Comment by ryanfrohar** [comment]
run tests

**Comment by ryanfrohar** [comment]
run tests

**Comment by TheColourRed** [comment]
Abandoning gradle due to jar file issues

**Pull request closed without merging**
